### ISSUE TITLE
[FR] Add Tab Colors

### ISSUE THREAD

**Issue by JohnLegrandRichards** [kamranahmedse/itomate#10]
Add ability to define tab colors
This could be RGB or have some predefined colors

example:

version: "1.0"
tabs:
  window-1:
    root: "~/Documents/Moxy-Projects/navblue-service"
    color: [255, 128, 128]
    title: "My Title"
    panes:
      - title: "A pane titler"
        position: "1/1"

**Comment by martin-braun** [comment]
[tabset](https://github.com/jonathaneunice/iterm2-tab-set) can do this, so you can do something like this: 

```yml
version: "1.0"
profile: "Default"
tabs:
  red:
    root: "$HOME"
    title: "red"
    panes:
      - position: "1/1"
        commands:
          - "tabset --color #ff0000"
          - "vim .env"
      - position: "1/2"
        commands:
          - "tabset --color #ff99ff"
          - "./wizard.ts -h"
  blue:
    root: "$HOME"
    title: "blue"
    panes:
      - position: "1/1"
        commands:
          - "tabset --color #0000ff"
          - "vim .env"
```

Unfortunately, it requires a node dependency and adds more overhead, making this thing even slower to launch. I would love to have this built into itomate.
