### ISSUE TITLE
[FR] Add ability to define Status Bar Components

### ISSUE THREAD

**Issue by JohnLegrandRichards** [kamranahmedse/itomate#12]
The new Status bar is really awesome. It would be nicd to be able to define what your status bar was comprised of. There would be one status bar for your iterm2 window.

```
version: "1.0"
status-bar: 
  - Battery-Level
  - User-Name
  - Empty-Space
  - Search-Tool
tabs:
  window-1:
    panes:
        position: "1/1"
```
