### ISSUE TITLE
[FR] Ability to set a root starting directory for all panes

### ISSUE THREAD

**Issue by JohnLegrandRichards** [kamranahmedse/itomate#6]
Ability needed to set a root directory for all panes in the tab. 

example:

```
version: "1.0"
tabs:
    window-1:
        root: "documents/projects/myproject"
        title: "my title"
```
